language: php

services:
  - docker

before_script:
  - if [ -n "$GIT_HUB_TOKEN" ]; then composer config -g github-oauth.github.com "$GIT_HUB_TOKEN"; fi;
  - composer install
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - make test-docker

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - version=5.6
  - version=7.0
  - version=7.1
  - version=7.2
  - version=7.3
  - version=7.4

jobs:
  include:
    - env: dependencies=lowest
    - env: dependencies=highest

notifications:
  slack:
    if: branch = master
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: R9JCklL/+TTher3FyJ2h3jFCnxkMHF8T9FszoOLfZeIR1hNADN9wqsLu8bItuKr3hcLzzR/1dG/rDQnHH2TmYuen0VSXBNoN/D1qGJPGayRrsAAUQXrcI9YVwdGwIcuoszM1GYFh3kQRf7RztUJeIw4P6Hl5WQyQC27UmflHK/M=
